target("triple_ecs")
    set_kind("moduleonly")
    add_files("*.mpp")
    add_deps("triple_base", "triple_refl")

target("triple_ecs-tests")
    set_kind("binary")
    add_files("tests/*.test.cpp")
    add_packages("catch2")
    add_deps("triple_ecs")